In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
south = pd.read_csv("south.csv")

In [23]:
south.head()

,index,Data,Hora,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),...,"VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",region,state,station,station_code,latitude,longitude,height
0,0,2000-09-22,00:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,S,RS,PORTO ALEGRE,A801,-30.05,-51.166667,46.97
1,1,2000-09-22,01:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,S,RS,PORTO ALEGRE,A801,-30.05,-51.166667,46.97
2,2,2000-09-22,02:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,S,RS,PORTO ALEGRE,A801,-30.05,-51.166667,46.97
3,3,2000-09-22,03:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,S,RS,PORTO ALEGRE,A801,-30.05,-51.166667,46.97
4,4,2000-09-22,04:00,0.0,1013.9,1014.2,1013.2,-9999,15.5,14.6,...,231,4.4,1.2,S,RS,PORTO ALEGRE,A801,-30.05,-51.166667,46.97

In [24]:
max_date = south['Data'].max()
min_date = south['Data'].min()

stations = south['station_code'].unique()

print(min_date, max_date)
print(stations)

start_date = '2020-04-30'

2000-09-22 2021-04-30
['A801' 'A804' 'A805' 'A803' 'A802' 'A806' 'A807' 'A824' 'A826' 'A808'
 'A819' 'A817' 'A829' 'A810' 'A828' 'A840' 'A818' 'A812' 'A813' 'A809'
 'A822' 'A823' 'A839' 'A820' 'A821' 'A835' 'A838' 'A855' 'A854' 'A841'
 'A851' 'A844' 'A811' 'A831' 'A836' 'A853' 'A830' 'A832' 'A827' 'A852'
 'A843' 'A845' 'A842' 'A847' 'A846' 'A875' 'A814' 'A860' 'A857' 'A878'
 'A863' 'A837' 'A856' 'A834' 'A859' 'A867' 'A869' 'A866' 'A871' 'A879'
 'A873' 'A899' 'A816' 'A850' 'A876' 'A858' 'A862' 'A815' 'A880' 'A849'
 'A861' 'A848' 'A833' 'A864' 'A868' 'A881' 'A874' 'A872' 'A883' 'A882'
 'A884' 'A865' 'B803' 'B806' 'A870' 'A897' 'A894' 'A889' 'A886' 'B804'
 'A893' 'A887' 'A825' 'A898' 'A895']

In [28]:
renamed_columns_en = ['date','hour','total precipitation (mm)','pressao atmosferica ao nivel da estacao (mb)','atmospheric pressure max. in the previous hour (mb)','atmospheric pressure min. in the previous hour (mb)','radiation (kj/m2)','air temperature - dry bulb (°c)','dew point temperature (°c)','max. temperature in the previous hour (°c)','min. temperature in the previous hour (°c)','dew temperature max. in the previous hour (°c)','dew temperature min. in the previous hour (°c)','relative humidity max. in the previous hour (%)','relative humidity min. in the previous hour (%)','air relative humidity (%)','wind direction (° (gr))','wind rajada maxima (m/s)','wind speed (m/s)','region','state','station','station_code','latitude','longitude','height']

def process_raw(df):
    """
    ! drop index
    ! rename the columns
    ! combine hour and date columns -> transform to date_time
    ! append columns data from all stations to keep the data granularity
    ! remove not useful columns
    ! return table 
    """
    df.drop(['index'],inplace=True, axis=1)
    df.columns = renamed_columns_en
    df['date_time'] = pd.to_datetime(df['date'] + ' ' +  df['hour'])
    df.drop(['date','hour','pressao atmosferica ao nivel da estacao (mb)','atmospheric pressure max. in the previous hour (mb)','atmospheric pressure min. in the previous hour (mb)','radiation (kj/m2)','air temperature - dry bulb (°c)','dew point temperature (°c)', 'dew temperature max. in the previous hour (°c)','dew temperature min. in the previous hour (°c)','air relative humidity (%)','wind direction (° (gr))','wind rajada maxima (m/s)'], inplace=True, axis=1)

    # station_codes = list(df.station_code.unique())
    # df_models = by_code(df,station_codes[0])
    # if len(station_codes)>1:
    #     for i in station_codes[1:]:
    #         df_temp = by_code(df,i)
    #         df_models = pd.concat([df_models,df_temp],axis=1)
    return df

# def by_code(df, station_code):
#     """
#     ! function that filters the dataframe by station_code and rename the columns by the status code
#     """
#     df_station = None
#     df_station = df[df['station_code'] == station_code]
#     df_station.index = df_station.iloc[:,-1]
#     df_station.drop(['station_code','date_time'],axis=1,inplace=True)
#     df_station.columns = list(map(lambda x: station_code+'_'+x, df_station.columns))
#     return df_station

# def clean_na(df, na_value = -9999):
#     """ 
#     ! replace Na from dataset
#     """
#     df = df.replace(to_replace=na_value,value=np.NaN)
#     df = df[df.iloc[:,1].first_valid_index():]
#     df = df.fillna(method='ffill')
#     return df

def make_dataset(stations, start_date, df):
    """
    ! filter raw data from date and stations code
    ! process data
    ! clean na
    """
    df = df[df['Data'] >= start_date]
    df = df[df['station_code'].apply(lambda x: x in stations)]
    df = process_raw(df)
    # df = clean_na(df)
    return df.reset_index()

In [29]:
south_Clean = make_dataset(stations,'2018-04-03', south)
south_Clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509080 entries, 0 to 2509079
Data columns (total 15 columns):
 #   Column                                           Dtype
---  ------                                           -----
 0   index                                            int64
 1   total precipitation (mm)                         float64
 2   max. temperature in the previous hour (°c)       float64
 3   min. temperature in the previous hour (°c)       float64
 4   relative humidity max. in the previous hour (%)  int64
 5   relative humidity min. in the previous hour (%)  int64
 6   wind speed (m/s)                                 float64
 7   region                                           object
 8   state                                            object
 9   station                                          object
 10  station_code                                     object
 11  latitude                                         float64
 12  longitude                                        float64
 13  height                                           float64
 14  date_time                                        datetime64[ns]
dtypes: datetime64[ns](1), float64(7), int64(3), object(4)
memory usage: 287.1+ MB

In [30]:
south_Clean = make_dataset(stations,'2018-04-03', south)
south_Clean

# the start_date variable I set up produces an empty table

,index,total precipitation (mm),max. temperature in the previous hour (°c),min. temperature in the previous hour (°c),relative humidity max. in the previous hour (%),relative humidity min. in the previous hour (%),wind speed (m/s),region,state,station,station_code,latitude,longitude,height,date_time
0,7576632,0.0,16.8,15.0,96,93,0.1,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-01 23:00:00
1,7576633,0.0,15.3,13.9,96,96,0.2,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 00:00:00
2,7576634,0.0,14.2,13.2,97,96,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 01:00:00
3,7576635,0.0,13.7,12.3,97,97,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 02:00:00
4,7576636,0.2,13.1,12.3,97,97,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 03:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2509075,10284883,0.0,21.6,20.7,40,36,4.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 19:00:00
2509076,10284884,0.0,20.9,20.1,40,36,3.2,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 20:00:00
2509077,10284885,0.0,20.1,18.4,47,40,2.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 21:00:00
2509078,10284886,0.0,18.5,17.5,51,46,2.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 22:00:00
2509079,10284887,0.0,17.5,14.8,62,51,3.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 23:00:00

In [34]:
# south_Clean.to_csv("2018_south.csv")

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
south = pd.read_csv("2018_south.csv")

In [3]:
def clean_na(df, na_value = -9999):
    """ 
    ! replace Na from dataset
    """
    df = df.replace(to_replace=na_value,value=np.NaN)
    df = df[df.iloc[:,1].first_valid_index():]
    df = df.fillna(method='ffill')
    return df

In [4]:
clean_na(south)

,Unnamed: 0,index,total precipitation (mm),max. temperature in the previous hour (°c),min. temperature in the previous hour (°c),relative humidity max. in the previous hour (%),relative humidity min. in the previous hour (%),wind speed (m/s),region,state,station,station_code,latitude,longitude,height,date_time
0,0,7576632,0.0,16.8,15.0,96.0,93.0,0.1,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-01 23:00:00
1,1,7576633,0.0,15.3,13.9,96.0,96.0,0.2,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 00:00:00
2,2,7576634,0.0,14.2,13.2,97.0,96.0,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 01:00:00
3,3,7576635,0.0,13.7,12.3,97.0,97.0,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 02:00:00
4,4,7576636,0.2,13.1,12.3,97.0,97.0,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 03:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2509075,2509075,10284883,0.0,21.6,20.7,40.0,36.0,4.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 19:00:00
2509076,2509076,10284884,0.0,20.9,20.1,40.0,36.0,3.2,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 20:00:00
2509077,2509077,10284885,0.0,20.1,18.4,47.0,40.0,2.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 21:00:00
2509078,2509078,10284886,0.0,18.5,17.5,51.0,46.0,2.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 22:00:00
2509079,2509079,10284887,0.0,17.5,14.8,62.0,51.0,3.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 23:00:00